export const SET_PLAYLIST_CATLIST = "SET_PLAYLIST_CATLIST";
export const SET_HQ_TAGLIST = "SET_HQ_TAGLIST";
export const SET_CONFIG_THEME = "SET_CONFIG_THEME";

export const SET_PLAYLIST_DETAIL = "SET_PLAYLIST_DETAIL";
export const SET_PLAYLIST_LOADING = "SET_PLAYLIST_LOADING";

export const SET_CREATED_PLAYLIST = "SET_CREATED_PLAYLIST";
export const SET_FAVED_PLAYLIST = "SET_FAVED_PLAYLIST";
export const SET_USER_LIKELIST = "SET_USER_LIKELIST";
export const SET_USER_LIKELISTIDS = "SET_USER_LIKELISTIDS";

export const SET_POSTING = "SET_POSTING";
export const SET_FETCHING = "SET_FETCHING";
